# Configuração do Mosquitto — Grupo 9
# ATENÇÃO: allow_anonymous true só é aceitável em laboratório local.
# Em produção seria obrigatório usuário/senha e TLS (porta 8883).

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type all
connection_messages true
